pull_request_rules:
  - name: Merge master into develop
    conditions:
      - base=develop
      - head=master
      - conflict false
      - 'status-success=ci/circleci: build'
      # - status-success=SonarCloud Code Analysis
      # - status-success=mergefreeze
    actions:
      merge:
        strict: true
  - name: Merge stub into develop
    conditions:
      - base=develop
      - head~=^meta/.*alpha$
      - approved
      - conflict false
      - author=@only-cklewin-and-testuser9891
    actions:
      merge:
        strict: true
  - name: Delete head branch after merge
    conditions:
      - head!=master
      - head~=^meta/.*alpha$
      - merged
    actions:
      delete_head_branch: {}
