pull_request_rules:
  - name: Merge master into develop
    conditions:
      - base=develop
      - head=master
      - 'status-success=ci/circleci: build'
      # - status-success=SonarCloud Code Analysis
      # - status-success=mergefreeze
      # - NEED TO ADD CHECK FOR AUTHOR/ACTOR is member of specific team
    actions:
      merge:
        strict: true
  - name: Merge stub into develop
    conditions:
      - base=develop
      - head~=^release/
    actions:
      merge:
        strict: true
  - name: Delete head branch after merge
    conditions:
      - head!=master
      - merged: true
    actions:
      delete_head_branch: {}
