pull_request_rules:
  - name: Merge master into develop
    conditions:
      - base=develop
      - head=master
      - 'status-success=ci/circleci: build'
      # - status-success=SonarCloud Code Analysis
      # - status-success=mergefreeze
    actions:
      merge:
        strict: true
  - name: Merge stub into develop
    conditions:
      - base=develop
      - head~=^meta/Release
    actions:
      merge:
        strict: true
  - name: Delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
