version: 2.1

jobs:
  check_sensitive_updates:
    docker:
      - image: circleci/python

    steps:
      - checkout

      - run:
          name: Sensitive files unchanged
          command: |
            git diff --exit-code origin/develop:.github HEAD:.github
            echo "Disabled"

  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

workflows:
  test_workflow:
    jobs:
      - check_sensitive_updates
      - build
