version: 2.1

jobs:
  check_sensitive_updates:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Sensitive files unchanged
          command: |
            git branch
            git status
            git diff develop
            git diff --exit-code develop:.github HEAD:.github

  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

workflows:
  test_workflow:
    jobs:
      - check_sensitive_updates
      - build
