name: Auto Approve PR on Release
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        if: github.head_ref == 'master' || startsWith('meta/Release:', github.head_ref) && github.base_ref == 'develop'
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
