name: Auto Approve PR on Release
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: team_member_logins
        uses: octokit/graphql-action@v2.x
        with:
          query: |
            query {
              organization (login:"jevaka-test-organization") {
                team(slug:"only-cklewin-and-testuser9891") {
                  members {
                    edges {
                      node {
                        login
                      }
                    }
                  }
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_READ_ORG_TOKEN }}

      - id: is_member_of_team
        run: " \
          jq -e '.organization.team.members.edges[] | \
            select(.node.login == \"${{ github.actor }}\") | \
            .node.login' <<< '${{ steps.team_member_logins.outputs.data }}' \
          2&>1 >> /dev/null"

      - id: approve_if_master_or_release_stub
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.head_ref == 'master' || startsWith('meta/', github.head_ref)
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
