name: Check Run

on:
  check_run:
    types:
      - completed

jobs:
  always-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Output github
        run: |
          echo $(jq '.' $GITHUB_EVENT_PATH)
