name: Release Manager Complete

on:
  pull_request_review:
    branches:
      - master
    types:
      - submitted

jobs:
  complete:
    if: (
      startsWith(github.event.pull_request.head.ref, 'release/') &&
      !github.event.pull_request.closed_at &&
      !github.event.pull_request.merged
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Checkout GitHub Action from private repo
        uses: actions/checkout@v3
        with:
          repository: sans-cpe/github-release-manager
          ref: feature/DOTS-402_display-errors-during-create-stage
          token: ${{ secrets.REPO_FULL_SCOPE_TOKEN }}
          path: .github/actions/github-release-manager

      - name: Complete release
        uses: ./.github/actions/github-release-manager
        with:
          github_token: ${{ secrets.REPO_FULL_SCOPE_TOKEN }}
          github_review_token: ${{ secrets.GITHUB_TOKEN }}
          production_branch: master
          integration_branch: develop
