name: Release Manager Cleanup

on:
  delete:

jobs:
  cleanup:
    if: startsWith(github.event.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Checkout GitHub Action from private repo
        uses: actions/checkout@v4
        with:
          repository: sans-cpe/github-release-manager
          ref: feature/DOTS-517_allow-rebase-merge
          token: ${{ secrets.REPO_FULL_SCOPE_TOKEN }}
          path: .github/actions/github-release-manager

      - name: Cleanup release
        uses: ./.github/actions/github-release-manager
        with:
          github_token: ${{ secrets.REPO_FULL_SCOPE_TOKEN }}
          production_branch: master
          integration_branch: develop
