name: Release

on:
  create:
  status:
  pull_request_review:
    types:
      - submitted

jobs:
  always-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Output github
        run: |
          echo $(jq '.' $GITHUB_EVENT_PATH)

  create:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - name: Validate CHANGELOG.md
        id: validate_changelog
        run: |
          echo "Validate CHANGELOG.md"
          echo "::set-env name=NEW_RELEASE_VERSION::$(echo 1.2.3)"

      - name: Freeze develop and master branches
        run: echo "Freeze branches"

      - name: Update version files
        run: echo "Modify CHANGELOG.md, package.json, package-lock.json with new release version"

      - name: Create release commit
        run: echo "Add version files, commit -m 'Release ${NEW_RELEASE_VERSION}'"

      - name: Create pull request to master
        run: echo "Open PR to master"

  merge:
    if: startsWith(github.event.pull_request.head.ref, 'release/') &&
      !github.event.pull_request.closed_at &&
      !github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request is mergeable
        run: |
          PR_REVIEWS=$(
            curl ${{ github.event.pull_request.url }}/reviews |
            jq '.[] |= { login: .user.login, state: .state } | reverse | unique_by( .login )'
          )

          PR_APPROVALS=$(
            echo ${PR_REVIEWS} |
            jq '[.[] | select( .state == "APPROVED" )] | length'
          )
          echo "::info ::This pull request has ${PR_APPROVALS} approvals"

          PR_CHANGE_REQUESTS=$(
            echo ${PR_REVIEWS} |
            jq '[.[] | select( .state == "CHANGES_REQUESTED" )] | length'
          )
          echo "::info ::This pull request has ${PR_CHANGE_REQUESTS} reviewers requesting changes"

          if [ ${PR_APPROVALS} -lt 1 ] || [ ${PR_CHANGE_REQUESTS} -gt 0 ]; then
            echo "::error ::Failed to meet pull request approval conditions"
            exit 1
          fi

          #
          # curl -H "Authorization: token $(git config github.token)" \
          # https://api.github.com/repos/jevaka-test-organization/test/branches/master/protection/required_status_checks
          #
          # Or we can check all statuses that are not THIS workflow
          #
          CHECK_RUNS=$(
            curl \
              -H "Authorization: token ${{ GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.antiope-preview+json" \
              ${{ github.event.pull_request.head.repo.url }}/commits/${{ github.event.pull_request.head.sha }}/check-runs |
            jq '.check_runs | .[] |= { name: .name, status: .status, conclusion: .conclusion }'
          )

          CHECK_RUNS_SUCCEEDED=$(
            echo ${CHECK_RUNS} |
            jq '[.[] | select( .conclusion == "success" )] | length'
          )
          echo "::info ::This pull request has ${CHECK_RUNS_SUCCEEDED} successful checks"

          CHECK_RUNS_INCOMPLETE=$(
            echo ${CHECK_RUNS} |
            jq '[.[] | select( .status != "completed" )] | length'
          )
          echo "::info ::This pull request has ${CHECK_RUNS_INCOMPLETE} incomplete checks"

          CHECK_RUNS_FAILED=$(
            echo ${CHECK_RUNS} |
            jq '[.[] | select( .conclusion == "failure" )] | length'
          )
          echo "::info ::This pull request has ${CHECK_RUNS_INCOMPLETE} failed checks"

          if [ ${CHECK_RUNS_INCOMPLETE} -gt 0 ] || [ ${CHECK_RUNS_FAILED} -gt 0 ]; then
            echo "::error ::Failed to meet check status conditions"
            exit 1
          fi

      - name: Merge into master
        run: echo "Merge into master"

      - name: Publish release
        run: echo "Publish release"

      - name: Create pull request from master to develop
        run: echo "Open PR from master to develop"

      - name: Auto-approve PR
        run: echo "Approve PR from master to develop"

      - name: Merge master into develop
        run: echo "Merge master into develop"

      - name: Create meta/stub-version-next_minor_version-alpha
        run: |
          echo "Create alpha stub branch (major.minor+1.0)"
          echo "::set-env name=ALPHA_STUB_VERSION::$(echo 1.3.0-alpha)"

      - name: Update version files
        run: echo "Modify CHANGELOG.md, package.json, package-lock.json with alpha version"

      - name: Create alphastub commit
        run: echo "Add version files, commit -m 'Stub version ${ALPHA_STUB_VERSION}'"

      - name: Create pull request from alphastub to develop
        run: echo "Open PR from alphastub to develop"

      - name: Auto-approve PR
        run: echo "Approve PR from alphastub to develop"

      - name: Merge alphastub into develop
        run: echo "Merge master into develop"

      - name: Unfreeze develop and master branches
        run: echo "Unfreeze branches"
