name: Release Manager Create

on:
  create:

jobs:
  create:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Checkout GitHub Action from private repo
        uses: actions/checkout@v4
        with:
          repository: sans-cpe/github-release-manager
          ref: feature/DOTS-517_allow-rebase-merge
          token: ${{ secrets.REPO_FULL_SCOPE_TOKEN }}
          path: .github/actions/github-release-manager

      - name: Create release
        uses: ./.github/actions/github-release-manager
        with:
          github_token: ${{ secrets.REPO_FULL_SCOPE_TOKEN }}
          github_review_token: ${{ secrets.GITHUB_TOKEN }}
          production_branch: master
          integration_branch: develop
          allow_integration_rebase_merge: true
          freeze_integration_branch: false
          tag_major: true
