name: Release Manager Create

on:
  create:
  delete:

jobs:
  create:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Checkout GitHub Action from private repo
        uses: actions/checkout@v3
        with:
          repository: sans-cpe/github-release-manager
          ref: feature/DOTS-255_add-merge-freeze-during-release
          token: ${{ secrets.REPO_FULL_SCOPE_TOKEN }}
          path: .github/actions/github-release-manager

      - name: Create release
        uses: ./.github/actions/github-release-manager
        with:
          github_token: ${{ secrets.REPO_FULL_SCOPE_TOKEN }}
          production_branch: master
          integration_branch: develop
