name: Release Manager

on:
  create:

jobs:
  create:
    if: startsWith(github.ref, 'refs/heads/release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # workaround to use a GitHub action from a private repo
      # https://github.community/t/github-action-action-in-private-repository/16063
      - name: Checkout GitHub action from private repo
        uses: actions/checkout@v2
        with:
          repository: sans-cpe/github-release-manager
          ref: feature/DOTS-129_add-python-about-version-file
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          path: .github/actions/github-release-manager

      - uses: ./.github/actions/github-release-manager
        with:
          github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          production_branch: master
          integration_branch: develop
